### ISSUE TITLE
ValueError: The 'ansible_doc_extractor.cli' package was not installed in a way that PackageLoader understands.

### ISSUE THREAD

**Issue by ricardojosegomezulmke** [xlab-steampunk/ansible-doc-extractor#10]
I believe this has to do with the jinja2 version, but not sure.
ansible version: 2.10.7
ansible-base: 2.10.9
jinja2: 3.0.1

pip install 'ansible<2.11'

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/bin/ansible-doc-extractor", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ansible_doc_extractor/cli.py", line 140, in main
    render_docs(args.output, args.module, args.template)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ansible_doc_extractor/cli.py", line 104, in render_docs
    template = get_template(custom_template)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ansible_doc_extractor/cli.py", line 92, in get_template
    env = Environment(loader=PackageLoader(__name__), trim_blocks=True)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/jinja2/loaders.py", line 310, in __init__
    f"The {package_name!r} package was not installed in a"
ValueError: The 'ansible_doc_extractor.cli' package was not installed in a way that PackageLoader understands.

**Comment by ricardojosegomezulmke** [comment]
after installing ansible, downgrading jinja2 works:

pip install --upgrade jinja2==2.11.2

**Comment by tadeboro** [comment]
Thank you, @ricardojosegomezulmke, for your bug report. I will investigate this ASAP.

**Comment by tadeboro** [comment]
Fixed in v0.1.7. Thank you again for reporting this.
