### ISSUE TITLE
Ansible 2.15 errors when using a doc fragment

### ISSUE THREAD

**Issue by ddimatos** [xlab-steampunk/ansible-doc-extractor#29]
Hi, 

First off, thank you for the product, its been incredibly helpful.

We have an error appear when using doc fragments (which is somewhat similar to issue #7 but not the same) (see traceback at bottom)
```
    raise AnsibleError('unknown doc_fragment(s) in file {0}: {1}'.format(filename, to_native(', '.join(unknown_fragments))))
ansible.errors.AnsibleError: unknown doc_fragment(s) in file ../plugins/modules/zos_copy.py: ibm.ibm_zos_core.template
```

We do have `ansible-doc-extractor` working with:
```
ansible-core==2.11.12
ansible-doc-extractor==0.1.5
```

Not working with:
```
ansible-core==2.15.2
ansible-doc-extractor==0.1.10
```

Things I tried:
```
export ANSIBLE_COLLECTIONS_PATHS=/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/doc_fragments; ansible-doc-extractor --template templates/module.rst.j2 source/modules ../plugins/modules/*.py

export DOC_FRAGMENT_PLUGIN_PATH=/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/doc;  ansible-doc-extractor --template templates/module.rst.j2 source/modules ../plugins/modules/*.py
```

I did some investigation up to a point and thought I should request help so I can remain on the right track:
- In 2.15, this code [resolved_fqcn](https://github.com/ansible/ansible/blob/3c8a3fa0af78c242e261a1f38bafb00c6f2e2f5b/lib/ansible/plugins/loader.py#L136) was added to PluginLoadContext.
- In 2.11 , the `resolved_fqcn` did not exist in [PluginLoadContext](https://github.com/ansible/ansible/blob/653b4fba7afce579477b18bb97f1043a4799f5a4/lib/ansible/plugins/loader.py#L115C7-L115C24)

I noticed a difference in in the object returned by [find_plugin_with_context](https://github.com/ansible/ansible/blob/653b4fba7afce579477b18bb97f1043a4799f5a4/lib/ansible/plugins/loader.py#L538) where:
   
- in 2.11 it looks correctly populated and discovered:
 ```
{'deprecated': False,
 'deprecation_warnings': [],
 'error_list': [],
 'exit_reason': 'found exact match for '
                'ansible_collections.ibm.ibm_zos_core.plugins.doc_fragments.template '
                'in ibm.ibm_zos_core',
 'import_error_list': [],
 'load_attempts': ['ibm.ibm_zos_core.template'],
 'original_name': 'ibm.ibm_zos_core.template',
 'pending_redirect': None,
 'plugin_resolved_collection': 'ibm.ibm_zos_core',
 'plugin_resolved_name': 'ansible_collections.ibm.ibm_zos_core.plugins.doc_fragments.template',
 'plugin_resolved_path': '/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/doc_fragments/template.py',
 'redirect_list': ['ibm.ibm_zos_core.template'],
 'removal_date': None,
 'removal_version': None,
 'resolved': True}
```
-in 2.15 not so fully discovered:
```
{'_resolved_fqcn': None,
 'action_plugin': None,
 'deprecated': False,
 'deprecation_warnings': [],
 'error_list': [],
 'exit_reason': 'ibm.ibm_zos_core is not eligible for last-chance resolution',
 'import_error_list': [],
 'load_attempts': ['/Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/lib/python3.10/site-packages/ansible/plugins/doc_fragments',
                   '/Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/lib/python3.10/site-packages/ansible/plugins/doc_fragments/__pycache__'],
 'original_name': 'ibm.ibm_zos_core',
 'pending_redirect': None,
 'plugin_resolved_collection': None,
 'plugin_resolved_name': None,
 'plugin_resolved_path': None,
 'redirect_list': ['ibm.ibm_zos_core'],
 'removal_date': None,
 'removal_version': None,
 'resolved': False}
```

In both 2.15 and 2.11 I can from the command line resolve doc which tells me `ANSIBLE_COLLECTIONS_PATHS` should resolve which confuses me to why I am having issues.

2.15:
```
(venv-2.15) ddimatos:[ ~/git/github/ibm_zos_core/docs ]ansible-doc ibm.ibm_zos_core.zos_copy
> IBM.IBM_ZOS_CORE.ZOS_COPY    (/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_copy.p>

        The zos_copy <./zos_copy.html> module copies a file or data set from a local or a remote machine
        to a location on the remote machine.

ADDED IN: version 1.2.0 of ibm.ibm_zos_core

  * note: This module has a corresponding action plugin.

OPTIONS (= is mandatory):

- backup
        Specifies whether a backup of the destination should be created before copying data.
        When set to `true', the module creates a backup file or data set.
        The backup file name will be returned on either success or failure of module execution such that
        data can be retrieved.
        default: false
        type: bool
```

2.11:
```
(venv-2.11) ddimatos:[ ~/git/github/ibm_zos_core/docs ]ansible-doc ibm.ibm_zos_core.zos_copy
> IBM.IBM_ZOS_CORE.ZOS_COPY    (/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_copy.p>

        The zos_copy <./zos_copy.html> module copies a file or data set from a local or a remote machine
        to a location on the remote machine.

  * note: This module has a corresponding action plugin.

OPTIONS (= is mandatory):

- backup
        Specifies whether a backup of the destination should be created before copying data.
        When set to `true', the module creates a backup file or data set.
        The backup file name will be returned on either success or failure of module execution such that
        data can be retrieved.
        [Default: False]
        type: bool

- backup_name
```

(venv-2.11) ddimatos:[ ~/git/github/ibm_zos_core/docs ]ansible-doc ibm.ibm_zos_core.zos_copy

Traceback:
```
Traceback (most recent call last):
  File "/Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/bin/ansible-doc-extractor", line 8, in <module>
    sys.exit(main())
  File "/Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/lib/python3.10/site-packages/ansible_doc_extractor/cli.py", line 175, in main
    render_docs(args.output, args.module, args.template, args.markdown)
  File "/Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/lib/python3.10/site-packages/ansible_doc_extractor/cli.py", line 128, in render_docs
    render_module_docs(output, module, template, extension)
  File "/Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/lib/python3.10/site-packages/ansible_doc_extractor/cli.py", line 66, in render_module_docs
    doc, examples, returndocs, metadata = plugin_docs.get_docstring(
  File "/Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/lib/python3.10/site-packages/ansible/utils/plugin_docs.py", line 239, in get_docstring
    add_fragments(data['doc'], filename, fragment_loader=fragment_loader, is_module=is_module)
  File "/Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/lib/python3.10/site-packages/ansible/utils/plugin_docs.py", line 214, in add_fragments
    raise AnsibleError('unknown doc_fragment(s) in file {0}: {1}'.format(filename, to_native(', '.join(unknown_fragments))))
ansible.errors.AnsibleError: unknown doc_fragment(s) in file ../plugins/modules/zos_copy.py: ibm.ibm_zos_core.template
```

I know this is mostly in the ansible code that the change occurred but before I engage that community, it would be great to hear back if there is something I am neglecting to do when using 2.15.

**Comment by hille721** [comment]
I can confirm, it is working with `ansible-core==2.14.9`, but not with  `ansible-core==2.15.3`

**Comment by mshonichev** [comment]
reproduced still as of `ansible-core==2.16.0`
