### ISSUE TITLE
Incompatibility with ansible-base 2.10 (beta)

### ISSUE THREAD

**Issue by sstanovnik** [xlab-steampunk/ansible-doc-extractor#8]
`ansible-doc-extractor` isn't compatible with `ansible-base`, because it (a-d-e) depends on `ansible`. Both are installed, which doesn't work.

## How to reproduce

```
saso@teh-destroyer ~> lxc launch images:debian/buster tadetest
saso@teh-destroyer ~> lxc exec tadetest bash
root@tadetest:~# apt update && apt install -y python3 python3-pip
root@tadetest:~# pip3 install ansible-base==2.10.0b1 ansible-doc-extractor
Collecting ansible-base==2.10.0b1
  Downloading https://files.pythonhosted.org/packages/14/40/8c71ee17f6568b831463fd0de02c8ff87227776bda688def4de4da30747e/ansible-base-2.10.0b1.tar.gz (5.7MB)
    100% |████████████████████████████████| 5.7MB 277kB/s 
Collecting ansible-doc-extractor
  Downloading https://files.pythonhosted.org/packages/df/a9/ee1c8973697153dad4fdb7c4629d40bc013409da68a53bc9a1f5b46fe29d/ansible_doc_extractor-0.1.4-py3-none-any.whl
Collecting PyYAML (from ansible-base==2.10.0b1)
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
    100% |████████████████████████████████| 276kB 3.2MB/s 
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ansible-base==2.10.0b1) (2.6.1)
Collecting jinja2 (from ansible-base==2.10.0b1)
  Downloading https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 3.2MB/s 
Collecting packaging (from ansible-base==2.10.0b1)
  Downloading https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting ansible (from ansible-doc-extractor)
  Downloading https://files.pythonhosted.org/packages/03/4f/cccab1ec2e0ecb05120184088e00404b38854809cf35aa76889406fbcbad/ansible-2.9.10.tar.gz (14.2MB)
    100% |████████████████████████████████| 14.2MB 115kB/s 
Collecting MarkupSafe>=0.23 (from jinja2->ansible-base==2.10.0b1)
  Downloading https://files.pythonhosted.org/packages/98/7b/ff284bd8c80654e471b769062a9b43cc5d03e7a615048d96f4619df8d420/MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from packaging->ansible-base==2.10.0b1) (1.12.0)
Collecting pyparsing>=2.0.2 (from packaging->ansible-base==2.10.0b1)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 4.9MB/s 
Building wheels for collected packages: ansible-base, PyYAML, ansible
  Running setup.py bdist_wheel for ansible-base ... done
  Stored in directory: /root/.cache/pip/wheels/87/71/8c/f9f3a1a5c71f1307c0476390d7d5218aee3cd87f09ec59bcba
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd
  Running setup.py bdist_wheel for ansible ... done
  Stored in directory: /root/.cache/pip/wheels/8a/60/dd/7fadf86fcbf2b9507d6fc5cf2ad57e3bd513111002d0701ba3
Successfully built ansible-base PyYAML ansible
Installing collected packages: PyYAML, MarkupSafe, jinja2, pyparsing, packaging, ansible-base, ansible, ansible-doc-extractor
Successfully installed MarkupSafe-1.1.1 PyYAML-5.3.1 ansible-2.9.10 ansible-base-2.10.0b1 ansible-doc-extractor-0.1.4 jinja2-2.11.2 packaging-20.4 pyparsing-2.4.7
```

## What I expect to happen

```
root@tadetest:~# ansible --version
ansible 2.10.0b1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.1 (default, Feb  2 2020, 08:49:34) [GCC 8.3.0]
```

## What happens instead

```
root@tadetest:~# ansible --version
ERROR! Unexpected Exception, this is probably a bug: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.7/dist-packages/ansible/utils/collection_loader/__init__.py)
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 92, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python3.7/dist-packages/ansible/cli/__init__.py", line 22, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/usr/local/lib/python3.7/dist-packages/ansible/inventory/manager.py", line 38, in <module>
    from ansible.plugins.loader import inventory_loader
  File "/usr/local/lib/python3.7/dist-packages/ansible/plugins/loader.py", line 26, in <module>
    from ansible.utils.collection_loader import AnsibleCollectionLoader, AnsibleFlatMapLoader, AnsibleCollectionRef
ImportError: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.7/dist-packages/ansible/utils/collection_loader/__init__.py)
```

**Comment by tadeboro** [comment]
I am not really sure we can do much here while retaining the same installation experience as before because, as far as I know, one cannot instruct python package to depend on *any* of the listed packages (in our case, we would need to somehow tell packaging machinery that we either need ansible or ansible-base).

Alternatives to this are that we force users to explicitly state what they will use as a "backend" by adding two extras: `ansible` and `ansible-base`. Users will then install extractor by running `pip install ansible-doc-extractor[ansible]` or `pip install ansible-doc-extractor[ansible-base]`.

Another option would be to transition away from the `ansible-doc-extractor` entirely and start using [antsibull-docs](https://github.com/ansible-community/antsibull). But we need to verify that the aforementioned tool is flexible enough for our use cases.

**Comment by ledroide** [comment]
Try this : 
* pip uninstall ansible ansible-base
* pip install ansible==2.9.14

**Comment by frankyhung93** [comment]
@ledroide This solved my issue entirely, Thanks!

**Comment by tadeboro** [comment]
The v0.1.7 and newer do not depend on the `ansible` package anymore. By default, the `pip install ansible-doc-extractor` will not install anything ansible-related. But we did add three extras:

 1. `pip install ansible-doc-extractor[ansible]` will also install the `ansible` package.
 2. `pip install ansible-doc-extractor[base]` will also install the `ansible-base` package.
 3. `pip install ansible-doc-extractor[core]` will also install the `ansible-core` package.
